### ISSUE TITLE
Keep getting errors in Visual Studio Code

### ISSUE THREAD

**Issue by NBAPJ** [cmdwtf/Odiin#95]
Hi every time I tryd to run a task in Visual Studio Code I get these Errors.

                   "-mfloat-abi=hard",
                "-mabi=aapcs",
                "-mfpu=fpv4-sp-d16"
            ],
            "compileCommands": "${workspaceFolder}/compile_commands.json"
   
Error 1 says that it cannot open cpptools-schema:/cpp_properties.schema.json. Detail resource in not avaiable (768) [1,1]

Error 2 says that it cannot find compile_commands.json [37,32]

Error 3 say Value is not accepted. Valid values: "msvc-x64, "gcc-x64", "clang-x64", "msvc-x86", "gcc-x86", "clang-x86", "$(default)". (1) [29,33]

**Comment by nitz** [comment]
Ah yeah, looks like I didn't include instructions to generate compile commands. They're not strictly necessary, and you could get around it by taking that line out of the `cpp_properties.json`, or just go ahead and generate them. From the console where you've got access to your python/pip: `pip install compiledb`, then `compiledb make` in the project folder should build and generate them!

**Comment by NBAPJ** [comment]
ok i removed the line now its saying this

{
	"resource": "/c:/Users/melenese/Desktop/Odiin/Odiin-main/.vscode/c_cpp_properties.json",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "768",
	"severity": 4,
	"message": "Request vscode/content failed with message: cannot open cpptools-schema:/c_cpp_properties.schema.json. Detail: resource is not available",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 2
}

**Comment by nitz** [comment]
From a quick google search, it looks like you should try re-starting vscode
as an administrator, then reinstall the cpp-tools extension. Looks like it
was a bug from an older version, but might still be present?

**Comment by NBAPJ** [comment]
I updated visual studio code to the latest version and reinstalled cpp but now its says this should i build things in a certain order I was trying to build the bootloader first.  This is really my first time doing a project like this.  I'm just so impressed by it I want to try and build one myself. 


make : The term 'make' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the 
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ make DEBUG=1
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (make:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by nitz** [comment]
You need [make](https://chocolatey.org/packages/make) on your path. The easiest way to get it on Windows is to install [Chocolatey](https://chocolatey.org/), and from your terminal run `choco install make` as an administrator.

**Comment by NBAPJ** [comment]
PS C:\Users\melenese> choco install make
choco : The term 'choco' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was 
included, verify that the path is correct and try again.
At line:1 char:1
+ choco install make

**Comment by nitz** [comment]
Did you go through the [installation steps](https://chocolatey.org/install) for chocolatey? 

If you do `Get-Command choco` does it point at `choco.exe`? Or give you a `not recognized`?

**Comment by NBAPJ** [comment]
Ok I'm back I have installed Chocolatey and when I ran the Get-Command choco it point the choco.exe.

PS C:\Windows\system32> Get-Command choco

CommandType     Name                                               ModuleName
-----------     ----                                               ----------
Application     choco.exe


PS C:\Windows\system32>

But now when I try to build something it gives me the error

Makefile:472: vendor/nRF5_SDK/components/toolchain/gcc/Makefile.common: No such file or directory
make: *** No rule to make target 'vendor/nRF5_SDK/components/toolchain/gcc/Makefile.common'.  Stop.
The terminal process "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command make bootloader" terminated with exit code: 1.

**Comment by nitz** [comment]
You either didn't clone the repository with the `--recurse-submodules` option, or you haven't run `git submodule update --init --recursive`. I make use of several submodules that have to be cloned as well.

**Comment by NBAPJ** [comment]
Yea thanks I went back and read over your build environment again and realized that I hadn't done that step.  Do you have an ETA on when you will post the Assembly Instructions?

**Comment by nitz** [comment]
I should be able to write up some instructions tomorrow. It's pretty
straightforward for the most part though, just soldering the bits together!

**Comment by nitz** [comment]
Discussion continued in #98
