### ISSUE TITLE
Off Topic Question

### ISSUE THREAD

**Issue by NBAPJ** [cmdwtf/Odiin#96]
Hi I have been talking to a couple of people that made the Disney Infinity Emulator that I mentioned and they said that creator coded the firmware so that when it installed on their board that it linked to their boards serial number and that the firmware they have would be useless to anyone else. Would it be possible to edit the firmware so that it doesn't link to the serial number and install on board?  He used st link v3

**Comment by nitz** [comment]
I'm not sure what they're referring to there. Serial number could mean any number of things in that regard. With regards to the firmware in general, typically firmware is very specific to the hardware it's written for, so it's unlikely for many reasons that it'd be useful outside of it's intended purpose.
